name: Create a GS code review
on:
 workflow_dispatch:
    inputs:
      featurebr:
        description: 'The feature branch for which you want to create a review.'
        required: true
        type: string
      ipreviewers:
        description: 'One ore more comma separated list of Github login names of users who need to approve the PR. Atleast one of these reviewers should be a GS IP reviewer - see gs-ipa-reviewers team in Github'
        required: true
        type: string
      parentofbase:
        description: 'The parent branch from which the base branch of PR will be created. You can leave it empty if you want the repo default branch to be used as parent'
        required: false
        type: string

jobs:
  create-gs-review-pr:
    uses: goldmansachs/gsoss-workflows/.github/workflows/create-pr.yml@main
    secrets: inherit
    with:
      featurebr: ${{ inputs.featurebr }}
      srcrepo: ${{ github.repository }}
      prauthor: ${{ github.actor }}
      parentofbase: ${{ inputs.parentofbase }}
      ipreviewers: ${{ inputs.ipreviewers }}
      mode: "real"
